/* Auto-generated by genmsg_cpp for file /home/fablab/ros_workspace/robair_demo/msg/encoderData.msg */
#ifndef ROBAIR_DEMO_MESSAGE_ENCODERDATA_H
#define ROBAIR_DEMO_MESSAGE_ENCODERDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robair_demo
{
template <class ContainerAllocator>
struct encoderData_ {
  typedef encoderData_<ContainerAllocator> Type;

  encoderData_()
  : wheelRight(0)
  , wheelLeft(0)
  {
  }

  encoderData_(const ContainerAllocator& _alloc)
  : wheelRight(0)
  , wheelLeft(0)
  {
  }

  typedef int32_t _wheelRight_type;
  int32_t wheelRight;

  typedef int32_t _wheelLeft_type;
  int32_t wheelLeft;


  typedef boost::shared_ptr< ::robair_demo::encoderData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robair_demo::encoderData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct encoderData
typedef  ::robair_demo::encoderData_<std::allocator<void> > encoderData;

typedef boost::shared_ptr< ::robair_demo::encoderData> encoderDataPtr;
typedef boost::shared_ptr< ::robair_demo::encoderData const> encoderDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robair_demo::encoderData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robair_demo::encoderData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robair_demo

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robair_demo::encoderData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robair_demo::encoderData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robair_demo::encoderData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "04f76768c4449761e9798eb41f5cfaf5";
  }

  static const char* value(const  ::robair_demo::encoderData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x04f76768c4449761ULL;
  static const uint64_t static_value2 = 0xe9798eb41f5cfaf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robair_demo::encoderData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robair_demo/encoderData";
  }

  static const char* value(const  ::robair_demo::encoderData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robair_demo::encoderData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 wheelRight\n\
int32 wheelLeft\n\
\n\
";
  }

  static const char* value(const  ::robair_demo::encoderData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robair_demo::encoderData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robair_demo::encoderData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.wheelRight);
    stream.next(m.wheelLeft);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct encoderData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robair_demo::encoderData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robair_demo::encoderData_<ContainerAllocator> & v) 
  {
    s << indent << "wheelRight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelRight);
    s << indent << "wheelLeft: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheelLeft);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBAIR_DEMO_MESSAGE_ENCODERDATA_H

